### ISSUE TITLE
please add name

### ISSUE THREAD

**Issue by lmrhody** [code4lib/c4l18-keynote-statement#134]
Please add Lisa Marie Rhody to signatures. Thank you.

**Comment by terrainsvagues** [comment]
Please add Nicky Agate too. Thank you!

**Comment by eyhayes-ncsu** [comment]
Please add Erica Hayes.  Thank you!

**Comment by EthanDF** [comment]
Please add Ethan Fenichel. Thank you!

**Comment by ranti** [comment]
Added. Thank you, all!
