### ISSUE TITLE
Is it worth trying to alphabetize the list of signatories?

### ISSUE THREAD

**Issue by matt-bernhardt** [code4lib/c4l18-keynote-statement#233]
Looking over how long this list has gotten, I wonder if it is worth trying to alphabetize the names? I'd be happy to take a crack at doing this - either just alphabetizing on the string as supplied by each signatory, or trying to apply a sort-by-last-name routine (which I realize might bring us into issues of how different communities prefer to do sorting).

No worries if we decide to leave things as is.

**Comment by gmcharlt** [comment]
I've no objection if you want to alphabetize, though I think the institutional ones (DLF, LITA, ACH, PKP, and the UVA Scholars' Lab) should end up kept together.

**Comment by ranti** [comment]
+1

**Comment by mjgiarlo** [comment]
Meh!

**Comment by mjgiarlo** [comment]
@matt-bernhardt @gmcharlt @ranti I whipped up https://github.com/code4lib/c4l18-keynote-statement/pull/246 so we could see what this looks like.

**Comment by ranti** [comment]
@mjgiarlo The groupings looks good to me. I appreciate the sorting by first name.

**Comment by matt-bernhardt** [comment]
I need to run a few errands at the moment, but I"m happy to put together a PR that implements the strategy laid out in #246 when I get back.

**Comment by thatandromeda** [comment]
I feel ++ on this in general but also I think it would be better to wait for a while - we are still getting a high volume of incoming signatories and will need to realphabetize before long; might be easier to wait until it's more stable.

**Comment by mjgiarlo** [comment]
@thatandromeda Do you think asking folks to add their names in sorted order is too high a bar? (Legit question, not asking it passive-aggressively.) If so, I think that's a good reason to wait.

**Comment by gmcharlt** [comment]
A suggestion once we decide we're ready to proceed - whoever prepares the final pull request, please give a shout here and in #general on the Slack to increase your chances that one of the folks adding signatures doesn't insta-create a merge conflict.

**Comment by matt-bernhardt** [comment]
I'm fine with waiting until things have calmed down a bit to try and tackle this.

**Comment by nowviskie** [comment]
I agree that it's a good idea to wait until things settle down!

**Comment by ranti** [comment]
I concur.

**Comment by thatandromeda** [comment]
@mjgiarlo I think it's too high a bar - for all that librarians are usually awesome at alphabetizing, we have an extremely large percentage of people whose first use of git/GitHub is signing this statement, and a bunch of merge conflicts.

(sorry I only just saw this - there are a LOT of emails from this repo in my inbox lately...)

**Comment by mjgiarlo** [comment]
Sounds good to me, @thatandromeda.

**Comment by thatandromeda** [comment]
OK, I *now* think it's a good idea; the rate of new PRs has declined significantly, and having the open issue is tempting people to put "add me" requests in comments rather than new issues, so I think the irritation of keeping the issue open now exceeds the irritation of closing it and having to redo it later ;)

**Comment by mjgiarlo** [comment]
@thatandromeda ha, ok, I can work on this in a wee bit.

**Comment by mjgiarlo** [comment]
@thatandromeda https://github.com/code4lib/c4l18-keynote-statement/pull/246 is ready for another look.

**Comment by mjgiarlo** [comment]
Thanks for creating this issue, @matt-bernhardt!
