### ISSUE TITLE
Please add me to the signatories list: Benjamin Albritton

### ISSUE THREAD

**Issue by blalbrit** [code4lib/c4l18-keynote-statement#411]
Please add me to the signatories list: Benjamin Albritton

**Comment by thatandromeda** [comment]
Done, and thanks.

**Comment by BarbaraBAW** [comment]
Would you add MIT Libraries to my name, which is Barbara Williams MIT Libraries

**Comment by BarbaraBAW** [comment]
Would you add MIT Libraries to my name, which is Barbara Williams MIT Libraries
