### ISSUE TITLE
Please add me to signatories in support of Chirs Bourg

### ISSUE THREAD

**Issue by mad1212** [code4lib/c4l18-keynote-statement#421]

**Comment by mayyanRye** [comment]
My pull request isn't going through, please add my signature as well thx - May Yan

**Comment by ranti** [comment]
@mayyanRye Added. Thank you.

@mad1212 Under what name should I add you?

**Comment by mayyanRye** [comment]
Thanks Ranti

**Comment by mad1212** [comment]
Marilyn Dunn

Thank you
