### ISSUE TITLE
Add my name in support of Chris

### ISSUE THREAD

**Issue by janemnichols** [code4lib/c4l18-keynote-statement#494]
Jane Nichols

**Comment by ranti** [comment]
Added. Thank you!

**Comment by 00Scribe18** [comment]
Add name to request: Celeste Â-Re, Ph.D

**Comment by gmcharlt** [comment]
@00Scribe18 I've added your name as well. Thanks!

**Comment by 00Scribe18** [comment]
Thank you!

--Celeste

"The last place the colonizer leaves is your mind" - Hari Kondabolu
* <https://en.wikipedia.org/wiki/Arundhati_Roy>*
  Celeste Â-Re
  2018 RadLAM Co-Coordinator



* <https://en.wikipedia.org/wiki/Arundhati_Roy>*
