### ISSUE TITLE
Sign letter for Chris Bourg

### ISSUE THREAD

**Issue by karenwilli** [code4lib/c4l18-keynote-statement#499]

**Comment by ranti** [comment]
@karenwilli - what name would you like me to put on the list?

**Comment by karenwilli** [comment]
Karen Williams.  Thanks.

Karen Williams
Vice President for Information Strategy and University Libraries

The University of Arizona
Tucson, Arizona 85721
Computer Center #201
Main Library A349

Phone: 520-621-5079

**Comment by ranti** [comment]
@karenwilli your name has been added to the list. Thank you!
