### ISSUE TITLE
add "Association of Southeastern Research Libraries (ASERL)" as organizational signatory

### ISSUE THREAD

**Issue by aserljeb** [code4lib/c4l18-keynote-statement#522]
Please add "Association of Southeastern Research Libraries (ASERL)" as an organizational signatory

**Comment by ranti** [comment]
Added. Thank you.

**Comment by aserljeb** [comment]
Thanks much!


--jeb

John Burger, Executive Director
Association of Southeastern Research Libraries (ASERL)
c/o Robert W. Woodruff Library
540 Asbury Circle, Suite 316
Atlanta, GA  30322

404-727-0137
