### ISSUE TITLE
add signature

### ISSUE THREAD

**Issue by ValGillispie** [code4lib/c4l18-keynote-statement#525]
I would like to add my signature to the statement. Thank you!

Valerie Gillispie
University Archivist
Duke University Archives
Rubenstein Rare Book & Manuscript Library
Box 90185
Durham, NC 27708-0185
Phone: 919-684-8929
Fax: 919-660-5934
Email: valerie.gillispie@duke.edu

**Comment by thatandromeda** [comment]
Done, and thanks.
