### ISSUE TITLE
Add signature

### ISSUE THREAD

**Issue by motropuk** [code4lib/c4l18-keynote-statement#532]
I would like to add my signature to the Code4Lib Community Statement in Support of Chris Bourg

Jonathan Manton
Music Librarian for Access Services
Irving S. Gilmore Music Library
Yale University
 
E: jonathan.manton@yale.edu
T: 203-432-5549
Tw: @jonmanton
W: http://web.library.yale.edu/music

**Comment by thatandromeda** [comment]
Done, and thanks.
