### ISSUE TITLE
Please add the British Columbia Library Association (BCLA)in support of c4l18-keynote-statement 

### ISSUE THREAD

**Issue by BCLibraryAssociation** [code4lib/c4l18-keynote-statement#534]
Please add the British Columbia Library Association (BCLA) to the list of organizations in support of c4l18-keynote-statement  #code4lib Community Statement in Support of Chris Bourg. Many thanks!

**Comment by thatandromeda** [comment]
Done, and thanks.

**Comment by BCLibraryAssociation** [comment]
Thank you!! Much appreciated!
